[phases.setup]
nixPkgs = ["libxcb", "xorg.libX11", "xorg.libXext", "xorg.libXrender"]

[phases.install]
cmds = [
  "pip install --upgrade pip",
  "pip uninstall -y opencv-python opencv-python-headless || true",
  "pip install opencv-python-headless",
  "pip install -r requirements.txt"
]